services:
  server:
    build:
      context: ./server
    container_name: 'server'
    volumes: 
      - '/usr/src/app'
    ports: 
      - 5000:5000
  client:
    build:
      context: ./client
    container_name: 'client'
    volumes: 
      - '/usr/src/app'
    ports: 
      - 3000:3000